apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend-deployment
  labels:
    app: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app   # <-- correction ici
    spec:
      containers:
      - name: backend
        image: babs32/projetfilrouge_backend
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5434"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: DB_NAME
          value: "mydb"
        - name: DB_SSLMODE
          value: "disable"
