apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfrontend-deployment
  labels:
    app: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name:  frontend
        image: babs32/projetfilrouge_frontend:latest  # remplace par l'image Docker de ton frontend
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myfrontend-service
spec:
  selector:
    app: frontend-app
  type: NodePort  # ou LoadBalancer si tu es sur un cloud ou Minikube avec tunnel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Port exposé sur la machine hôte (facilement testable sur Minikube)
