pipeline {
  agent any

  stages {
    stage('Deploy to Kubernetes') {
      steps {
        sh 'kubectl apply -f k8s/frontend.yaml'
        sh 'kubectl apply -f k8s/backend.yaml'
      }
    }
  }
}
